config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :bookmarks
  end
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :topics
  end
  resources :bookmarks, except: [:index] do
     resources :likes, only: [:index, :create, :destroy]
   end 
  get 'welcome/index'

  get 'welcome/about'
  root 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @topic = Topic.find(params[:topic_id])
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new
    @bookmark.user = current_user
    @bookmark.url = params[:bookmark][:url]
    @topic = Topic.find(params[:topic_id])
    @bookmark.topic = @topic
    if @bookmark.save
      flash[:notice] = 'Bookmark was saved.'
      redirect_to [@topic, @bookmark]
    else
      flash.now[:alert] = 'There was an error saving the bookmark. Please try again.'
      render :new
    end
end

  def update
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    @bookmark.url = params[:bookmark][:url]

    if @bookmark.save
      flash[:notice] = 'Bookmark was updated.'
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash.now[:alert] = 'There was an error saving the bookmark. Please try again.'
      render :edit
    end
    end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
      redirect_to @bookmark.topic
    else
      flash.now[:alert] = 'There was an error deleting the bookmark.'
      render :show
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for bookmarks</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@bookmark.topic, @bookmark] do |f| %>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/index.html.erb
<div class="row">
  <div class="col-md-8">

    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to @topic.title, @topic %>
        </h4>
        <% @topic.bookmarks.each do |bookmark| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to bookmark.url, bookmark.url %>
            </h4>
            <small>
                submitted <%= time_ago_in_words(bookmark.created_at) %> ago <br>
              </small>
          </div>
        </div>
        <% end %>
        <small>


        </small>
      </div>
    </div>


  </div>
  <div class="col-md-4">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for bookmarks</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
  <%= form_for [@topic, @bookmark] do |f| %>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.url %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @bookmark.url %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@bookmark).update? %>
    <%= link_to "Edit Bookmark", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@bookmark).destroy? %>
    <%= link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' } %>
    <% end %>
    <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
  </div>
</div>