config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :bookmarks
  end
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :topics
  end
  resources :bookmarks, except: [:index] do
     resources :likes, only: [:index, :create, :destroy]
   end 
  get 'welcome/index'

  get 'welcome/about'
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
    has_many :bookmarks, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
     @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
  @topic = Topic.new
  @topic.title = params[:topic][:title]
  @topic.user = current_user
  if @topic.save
    flash[:notice] = "Topic was saved."
    redirect_to @topic
  else
    flash.now[:alert] = "There was an error saving the topic. Please try again."
    render :new
  end
end

def update
    @topic = Topic.find(params[:id])
    authorize @topic
    @topic.title = params[:topic][:title]

    if @topic.save
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "There was an error saving the topic. Please try again."
      render :edit
    end
  end


   def destroy
     @topic = Topic.find(params[:id])
     authorize @topic
     if @topic.destroy
       flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
       redirect_to topics_path
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Topics</p>
     <ul>
       <li>Blocmarks topics</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
<h1>Blocmarks Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h2 class="media-heading">
          <%= link_to topic.title, topic_bookmarks_path(topic) %>
        </h2>
        <% topic.bookmarks.each do |bookmark| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to bookmark.url, topic_bookmark_path(topic, bookmark) %>
              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
            </h4>
            <small>
                submitted <%= time_ago_in_words(bookmark.created_at) %> ago <br>
              </small>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic title" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<% if policy(@topic).update? %>
<%= link_to "Edit", edit_topic_path(@topic), class: 'btn btn-success' %>
<% end %>
<% if policy(@topic).destroy? %>
<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'} %>
<% end %>
<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.title %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
  </div>
</div>